"""initial

Revision ID: 90cc04ad5804
Revises:
Create Date: 2025-06-08 15:15:45.569950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90cc04ad5804'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refuel',
    sa.Column('odometer', sa.Float(), nullable=False, comment='Текущий пробег в км.'),
    sa.Column('fuel_volume', sa.Float(), nullable=False, comment='Объем заправленного бака в литрах'),
    sa.Column('is_full', sa.Boolean(), nullable=False, comment='Заправка до полного бака.'),
    sa.Column('skipped_previous', sa.Boolean(), nullable=False, comment='Пропущена предыдущая заправка.'),
    sa.Column('id', sa.Integer(), nullable=False, comment='Уникальный идентификатор'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания записи.'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Дата и время редактирования записи.'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refuel')
    # ### end Alembic commands ###
